# typed: false
# frozen_string_literal: true

# This file is generated by scripts/release-cli.sh — do not edit by hand.
class Exo < Formula
  desc "Command-line client for the Exo platform"
  homepage "https://github.com/adaptive-scale/exo"
  version "0.2.266"

  on_macos do
    on_arm do
      url "https://exo.assets.adaptive.live/exo/0.2.266/exo_0.2.266_darwin_arm64.tar.gz"
      sha256 "02e3112f39b3e57bf674efb459ed980e3f8acc680bf786c69c6d66271efa741a"
    end
    on_intel do
      url "https://exo.assets.adaptive.live/exo/0.2.266/exo_0.2.266_darwin_amd64.tar.gz"
      sha256 "c732891ba14337b538911727c3ab71a3bd62f284aa1d66e96eb48108c3d972f4"
    end
  end

  on_linux do
    on_arm do
      url "https://exo.assets.adaptive.live/exo/0.2.266/exo_0.2.266_linux_arm64.tar.gz"
      sha256 "9e5dc389957682934a01d992b01adab638f0942f476ec27722614b0859b10559"
    end
    on_intel do
      url "https://exo.assets.adaptive.live/exo/0.2.266/exo_0.2.266_linux_amd64.tar.gz"
      sha256 "e0d7c6171e09ffd09525de702d3ee1c0c3d424b39dd2b55cbb2ec998dc580fff"
    end
  end

  def install
    bin.install "exo"
  end

  test do
    assert_match "0.2.266", shell_output("#{bin}/exo version")
  end
end
