# typed: false
# frozen_string_literal: true

# This file is generated by scripts/release-cli.sh — do not edit by hand.
class Exo < Formula
  desc "Command-line client for the Exo platform"
  homepage "https://github.com/adaptive-scale/exo"
  version "0.2.344"

  on_macos do
    on_arm do
      url "https://exo.assets.adaptive.live/exo/0.2.344/exo_0.2.344_darwin_arm64.tar.gz"
      sha256 "cf7e695f865af395302812f98ad0a608ac3fb2e67fd2681cf51c49f804715784"
    end
    on_intel do
      url "https://exo.assets.adaptive.live/exo/0.2.344/exo_0.2.344_darwin_amd64.tar.gz"
      sha256 "a422442f02f8cba4b574f369390e262f065e4e3de22569afd1ac74558f535801"
    end
  end

  on_linux do
    on_arm do
      url "https://exo.assets.adaptive.live/exo/0.2.344/exo_0.2.344_linux_arm64.tar.gz"
      sha256 "848ebc0bd8fcd670b780d72fa7ecb05d9ec81f0edb71796a2761aed5326742ed"
    end
    on_intel do
      url "https://exo.assets.adaptive.live/exo/0.2.344/exo_0.2.344_linux_amd64.tar.gz"
      sha256 "11dc2893b29c4cac97dd6db8551a33f05216241ae423327ab77e54c47a4493e3"
    end
  end

  def install
    bin.install "exo"
  end

  test do
    assert_match "0.2.344", shell_output("#{bin}/exo version")
  end
end
